#!/usr/bin/env python3
"""Turn the book's LaTeX table of contents into _data/toc.yml.

Emitting data rather than a finished page keeps the contents listing and the
prose that introduces it apart: _book/table-of-contents.md owns the words and
loops over what this writes. Re-run after a rebuild of the book:

    ./tools/generate_toc.py --manuscript ../manuscripts/everyday-programming
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from extract_exercises import _read_group, latex_to_markdown  # noqa: E402

CONTENTSLINE = re.compile(r"\\contentsline \{(part|chapter|section)\}\{")

# minted's inline macro survives into the .toc in its fully expanded,
# write-safe form. Collapsing it back to \mintinline lets the shared converter
# handle it, so `\py{if}` in a section title reaches the page as `if` in code
# style rather than as a wall of FVExtra internals.
FVEXTRA = r"\FVExtraRobustCommand \RobustMintInline \FVExtraAlwaysUnexpanded "
FVEXTRA_INNER = r"\FVExtraUnexpandedReadStarOArgMArgBVArg "


def normalise_minted(src: str) -> str:
    out, i = [], 0
    while True:
        j = src.find(FVEXTRA, i)
        if j < 0:
            out.append(src[i:])
            return "".join(out)
        out.append(src[i:j])
        group, after = _read_group(src, j + len(FVEXTRA))
        inner = group.strip()
        if inner.startswith(FVEXTRA_INNER.strip()):
            rest = inner[len(FVEXTRA_INNER.strip()):].lstrip()
            k = _read_group(rest, 0)[1]      # skip the {python} language argument
            code = _read_group(rest, k)[0]
            out.append("\\mintinline{python}{" + code + "}")
        else:
            out.append(inner)
        i = after


def clean(title: str) -> str:
    title = normalise_minted(title)
    title = re.sub(r"\\xpg@aux \{[^}]*\}\{[^}]*\}", "", title)
    title = re.sub(r"\\hspace \{[^}]*\}", " ", title)
    return latex_to_markdown(title)


def parse_toc(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    parts: list[dict] = []
    current_chapter: dict | None = None

    for match in CONTENTSLINE.finditer(text):
        kind = match.group(1)
        body, after = _read_group(text, match.end() - 1)
        page_str, _ = _read_group(text, after)

        number = ""
        num = re.match(r"\\numberline \{([^}]*)\}", body)
        if num:
            number, body = num.group(1), body[num.end():]

        title = clean(body)
        try:
            page = int(page_str)
        except ValueError:
            continue

        if kind == "part":
            # Parts carry their numeral inside the title: "I\hspace{1em}Basic
            # Concepts". Split it back off so the page can style the two.
            numeral, _, name = title.partition(" ")
            parts.append({"part": numeral.strip(), "title": name.strip() or numeral,
                          "page": page, "chapters": []})
            current_chapter = None
        elif kind == "chapter":
            if not parts:
                parts.append({"part": "", "title": "", "page": page, "chapters": []})
            current_chapter = {"number": number, "title": title,
                               "page": page, "sections": []}
            parts[-1]["chapters"].append(current_chapter)
        elif kind == "section" and current_chapter is not None:
            current_chapter["sections"].append(
                {"number": number, "title": title, "page": page})
    return parts


def yaml_escape(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(parts: list[dict]) -> str:
    lines = [
        "# Generated by tools/generate_toc.py from everyday-programming.toc.",
        "# Do not edit by hand; re-run the script after rebuilding the book.",
    ]
    for part in parts:
        lines += [
            f"- part: {yaml_escape(part['part'])}",
            f"  title: {yaml_escape(part['title'])}",
            f"  page: {part['page']}",
            "  chapters:",
        ]
        for ch in part["chapters"]:
            lines += [
                f"    - number: {yaml_escape(ch['number'])}",
                f"      title: {yaml_escape(ch['title'])}",
                f"      page: {ch['page']}",
            ]
            if ch["sections"]:
                lines.append("      sections:")
                for sec in ch["sections"]:
                    lines += [
                        f"        - number: {yaml_escape(sec['number'])}",
                        f"          title: {yaml_escape(sec['title'])}",
                        f"          page: {sec['page']}",
                    ]
            else:
                lines.append("      sections: []")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manuscript", type=Path,
                        default=Path("../manuscripts/everyday-programming"))
    parser.add_argument("--site", type=Path, default=Path("."))
    args = parser.parse_args()

    toc = args.manuscript.expanduser().resolve() / "everyday-programming.toc"
    if not toc.exists():
        sys.exit(f"error: {toc} not found -- build the book first")

    parts = parse_toc(toc)
    chapters = sum(len(p["chapters"]) for p in parts)
    sections = sum(len(c["sections"]) for p in parts for c in p["chapters"])
    if chapters < 20:
        sys.exit(f"error: only {chapters} chapters parsed; the .toc looks incomplete")

    out = args.site.expanduser().resolve() / "_data" / "toc.yml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(parts), encoding="utf-8")

    last = max(c["page"] for p in parts for c in p["chapters"])
    print(f"{len(parts)} parts, {chapters} chapters, {sections} sections "
          f"-> {out.relative_to(args.site.expanduser().resolve())} (last page {last})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
